spring.datasource.url=jdbc:postgresql://aws-1-eu-west-3.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.axhxbtgpdkekevgvbvkp
spring.datasource.password=M2airbnbmiage@
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.auth.token-secret=rentEasyJwtSecret_2026_k9F2xL7mQ1pR8tV4wZ6nC3dH5sB0yU9aE2
app.security.password-pepper=rentEasyPasswordPepper_2026_A8xM4qT1nL7vP2sK9dH5cR3wY6zB0
