spring.datasource.url=jdbc:postgresql://aws-1-eu-west-3.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.axhxbtgpdkekevgvbvkp
spring.datasource.password=M2airbnbmiage@
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.auth.token-secret=rentEasyJwtSecret_2026_k9F2xL7mQ1pR8tV4wZ6nC3dH5sB0yU9aE2
app.security.password-pepper=rentEasyPasswordPepper_2026_A8xM4qT1nL7vP2sK9dH5cR3wY6zB0

# Hikari (pool optimisé Supabase)
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.max-lifetime=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.auto-commit=false

# Hibernate + PgBouncer
spring.jpa.properties.hibernate.connection.provider_disables_autocommit=true

# Bonne pratique
spring.jpa.open-in-view=false

